# Generated by Django 5.1.4 on 2025-03-24 14:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveCfdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePila', models.CharField(max_length=255)),
                ('apPaterno', models.CharField(max_length=255)),
                ('apMaterno', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('codigoPostalCliente', models.CharField(blank=True, max_length=10, null=True)),
                ('ciudadCliente', models.CharField(blank=True, max_length=255, null=True)),
                ('estadoCliente', models.CharField(blank=True, max_length=255, null=True)),
                ('coloniaCliente', models.CharField(blank=True, max_length=255, null=True)),
                ('numeroCliente', models.CharField(blank=True, max_length=10, null=True)),
                ('calleCliente', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fechaPago', models.DateTimeField()),
                ('facturama_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rfc', models.CharField(max_length=13)),
                ('codigoPostal', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('colonia', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('calle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True, null=True)),
                ('ordenCompra', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaExpedicion', models.DateTimeField()),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipoMoneda', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenMarcaAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='marca_agua/')),
            ],
        ),
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Metodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegimenFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCfdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('abreviatura', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadCfdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsoCfdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=255)),
                ('fechaSolicitud', models.DateField()),
                ('fechaCaducidad', models.DateField()),
                ('descuento', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iva')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.CreateModel(
            name='ComprobantePagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montototal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montorestante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montopago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcialidad', models.PositiveIntegerField(blank=True, null=True)),
                ('comprobantepago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comprobantepago')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.factura')),
            ],
        ),
        migrations.AddField(
            model_name='comprobantepago',
            name='factura',
            field=models.ManyToManyField(through='core.ComprobantePagoFactura', to='core.factura'),
        ),
        migrations.CreateModel(
            name='FacturaFacturama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField()),
                ('idfactura', models.TextField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.factura')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='formaPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formapago'),
        ),
        migrations.AddField(
            model_name='comprobantepago',
            name='formapago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formapago'),
        ),
        migrations.CreateModel(
            name='InfoCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFormato', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('fechaEmision', models.DateField()),
                ('tituloDocumento', models.CharField(max_length=255)),
                ('mensajePropuesta', models.TextField()),
                ('termino', models.TextField()),
                ('avisos', models.TextField()),
                ('imagenMarcaAgua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagenmarcaagua')),
            ],
        ),
        migrations.CreateModel(
            name='InfoOrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFormato', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('fechaEmision', models.DateField()),
                ('tituloDocumento', models.CharField(max_length=255)),
                ('imagenMarcaAgua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagenmarcaagua')),
            ],
        ),
        migrations.CreateModel(
            name='InfoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCambioDolar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iva')),
                ('tipoMoneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipomoneda')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='metodoPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.metodopago'),
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=255, unique=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cotizacion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='ordenTrabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordentrabajo'),
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('colonia', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('calle', models.CharField(max_length=255)),
                ('codigoPostal', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=255)),
                ('slogan', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('pagina', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('infoCotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.infocotizacion')),
                ('infoOrdenTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.infoordentrabajo')),
                ('infoSistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.infosistema')),
                ('RegimenFiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.regimenfiscal')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
        ),
        migrations.CreateModel(
            name='CertificadoSelloDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=255)),
                ('archivocer', models.FileField(upload_to='certificados/')),
                ('archivokey', models.FileField(upload_to='certificados/')),
                ('contrasenia', models.CharField(max_length=255)),
                ('Organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='PreCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(max_length=255)),
                ('nombreCliente', models.CharField(max_length=255)),
                ('apellidoCliente', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('denominacion', models.CharField(max_length=255)),
                ('fechaSolicitud', models.DateField()),
                ('fechaCaducidad', models.DateField()),
                ('descuento', models.IntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iva')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePila', models.CharField(max_length=255)),
                ('apPaterno', models.CharField(max_length=255)),
                ('apMaterno', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion')),
            ],
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receptor'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regimenFiscal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.regimenfiscal'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organizacion')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rol')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claveCfdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clavecfdi')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
                ('metodos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.metodos')),
                ('objetoImpuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.objetoimpuesto')),
                ('unidadCfdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadcfdi')),
            ],
        ),
        migrations.CreateModel(
            name='PreCotizacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('preCotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.precotizacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='precotizacion',
            name='servicio',
            field=models.ManyToManyField(through='core.PreCotizacionServicio', to='core.servicio'),
        ),
        migrations.CreateModel(
            name='OrdenTrabajoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('ordenTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordentrabajo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='servicio',
            field=models.ManyToManyField(through='core.OrdenTrabajoServicio', to='core.servicio'),
        ),
        migrations.CreateModel(
            name='CotizacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cotizacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='servicios',
            field=models.ManyToManyField(through='core.CotizacionServicio', to='core.servicio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipoCfdi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipocfdi'),
        ),
        migrations.AddField(
            model_name='precotizacion',
            name='tipoMoneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipomoneda'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipoMoneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipomoneda'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='titulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.titulo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='UsoCfdi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usocfdi'),
        ),
    ]
