# Generated by Django 5.1.4 on 2025-04-28 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ordentrabajo_numero_precotizacion_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numeroExterior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='porcentaje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metodos',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metodos',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
