# Generated by Django 5.1.4 on 2025-04-29 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_division_cliente_numero_cotizacion_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='ordenTrabajo',
        ),
        migrations.AddField(
            model_name='factura',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cotizacion'),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FacturaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.factura')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='servicio',
            field=models.ManyToManyField(through='core.FacturaServicio', to='core.servicio'),
        ),
    ]
